//created on: 20-ott-2014
package rules.giomes.sample2;

import com.sample2.domain.Room;
import com.sample2.domain.Sprinkler;
import com.sample2.domain.Fire;

rule "When the fire is gone turn off the sprinkler"
when
    $room : Room( )
    $sprinkler : Sprinkler( room == $room, on == true )
    not Fire( room == $room )
then
    modify( $sprinkler ) { setOn( false ) };
    System.out.println( "Turn off the sprinkler for room " + $room.getName() );
end

